### ISSUE TITLE
Error when adding module to page.

### ISSUE THREAD

**Issue by leedavi** [i502Club/WebConfigEncryptor#1]
![image](https://user-images.githubusercontent.com/5583141/159901009-fa35768f-2b3b-4264-ae65-8a0bd3d8e5b5.png)

**Comment by i502Club** [comment]
Thanks for the heads up.  Let me know if the fresh install still has issues.

**Comment by leedavi** [comment]
Have you uploaded the new one to GitHUb??  The verison is still the same

**Comment by leedavi** [comment]
OK All good.  Working now.
